name: Engine KVDB Integration Test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the engine base branch and with changes in the src/engine/ directory.
  pull_request:
    types:
      - ready_for_review
      - synchronize
    branches:
      - 11334-dev-new-wazuh-engine
    paths:
      - 'src/engine/**'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only one instance of this workflow is running per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUILD_TYPE: Release
  ENGINE_DIR: ${{github.workspace}}/src/engine

jobs:
  build:
    name: Engine KVDB Integration Test

    # Runs only if the PR status is different to Draft
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache CMake and ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.workflow }}-${{ runner.os }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      # Install behave
      run: |
        pip install ${{env.ENGINE_DIR}}/test/integration_tests/engine-integration-test/
        pip install behave

    - name: Configure CMake
      # Configure the CMake build system with the specified build type
      run: cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.ENGINE_DIR}} -B ${{env.ENGINE_DIR}}/build

    - name: Build
      # Build the specified target using CMake
      run: cmake --build ${{env.ENGINE_DIR}}/build --config ${{env.BUILD_TYPE}} --target all -j2

    - name: Set Server Configuration
      # Set Server Configuration
      run: bash ${{env.ENGINE_DIR}}/test/integration_tests/buildEnvironment.sh ${{github.workspace}}

    - name: Integration Test
      # Run integration tests using behave
      run: bash ${{env.ENGINE_DIR}}/test/integration_tests/run.sh ${{github.workspace}}
